version: "3.8"

networks:
  tooling:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.11.0/24

services:
  # Git server. We need a small one in order to run on a single machine. Can be replaced with any.
  gitea: 
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    networks:
      tooling:
        ipv4_address: 172.16.11.3     
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 3000:3000
#      - 322:22
    depends_on:
      - db

  db:
    container_name: gitea_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      tooling:
        ipv4_address: 172.16.11.4     
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

# NetCICD Toolbox, containing TACACS, RADIUS,syslog, SNMP
  toolbox:
    container_name: toolbox
    build: ./toolbox
    restart: always
    networks:
      tooling:
        ipv4_address: 172.16.11.6     
#    ports:
#      - 622:22/tcp
#      - 49:49/tcp
#      - 161:161/udp
#      - 162:162/udp
#      - 514:514/udp
#      - 1812:1812/udp
#      - 1813:1813/udp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

# jenkins
  jenkins:
    container_name: jenkins
    build: ./jenkins
    privileged: true
    user: root
    networks:
      tooling:
        ipv4_address: 172.16.11.8     
#    ports:
#      - 822:22/udp
#      - 8081:8080
#      - 50000:50000
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - ./jenkins/sock:/var/run/docker.sock
      - ./jenkins/docker:/usr/local/bin/docker
      - ./jenkins/config:/var/jenkins_conf
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf

# Nexus
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    volumes:
      - ./nexus/data:/sonatype-work
    networks:
      tooling:
        ipv4_address: 172.16.11.9     
#    ports:
#      - 922:22/udp
#      - 8082:8081

# Argos
  argos:
    container_name: argos
    image: argosnotary/argosnotary
    volumes:
      - ./argos/data:/data/db
      - ./argos/config:/data/configdb
      networks:
        tooling:
          ipv4_address: 172.16.11.10    
  #    ports:
  #      - 1080:80
  #      - 8090:8080
  #      - 8087:8087
  
# Conjur

