version: "3.8"

networks:
  tooling:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.11.0/24
  jumphosts:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.111.0/24
  keycloak:
  reverse-proxy:
      
services:
  # NetCICD database: we need a central location to store data
  netcicd-db:
    container_name: netcicd-db
    build: netcicd-db
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=gitea,keycloak
      - POSTGRES_USER=netcicd
      - POSTGRES_PASSWORD=netcicd

    networks:
      tooling:
        ipv4_address: 172.16.11.2     
    volumes:
      - ./netcicd-db/db:/var/lib/postgresql/data
  
  # Git server. We need a small one in order to run on a single machine. Can be replaced with any.
  gitea: 
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=172.16.11.3
      - SSH_DOMAIN=172.16.11.3
      - DB_TYPE=postgres
      - DB_HOST=netcicd-db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    networks:
      tooling:
        ipv4_address: 172.16.11.3     
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000"
#    ports:
#      - 3000:3000
#      - 322:22
    depends_on:
      - netcicd-db
      - keycloak

 # NetCICD Toolbox, containing TACACS, RADIUS,syslog, SNMP
  toolbox:
    container_name: toolbox
    build: ./toolbox
    restart: always
    networks:
      tooling:
        ipv4_address: 172.16.11.6     
#    ports:
#      - 622:22/tcp
#      - 49:49/tcp
#      - 161:161/udp
#      - 162:162/udp
#      - 514:514/udp
#      - 1812:1812/udp
#      - 1813:1813/udp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

#Jenkins-node
  jenkins-node:
    container_name: jenkins_node
    build: ./jenkins_node
    privileged: true
    user: root
    networks:
      tooling:
        ipv4_address: 172.16.11.7     

# jenkins
  jenkins:
    container_name: jenkins
    build: ./jenkins
    privileged: true
    user: root
    networks:
      tooling:
        ipv4_address: 172.16.11.8     
#    ports:
#      - 822:22/udp
#      - 8081:8080
#      - 50000:50000
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=netcicd
      - NETCICD_PASSWORD=netcicd
      - CML_USER=guest
      - CML_PASSWORD=guest
      - CML_URL=http://172.16.32.148:19399
      - GIT_JENKINS_PASSWORD=netcicd
      - NEXUS_JENKINS_PASSWORD=netcicd
      - ARGOS_JENKINS_PASSWORD=netcicd
      - JENKINS_AGENT_CREATOR=netcicd
      - JENKINS_AGENT_CREATOR_KEY=somekey
    depends_on:
      - jenkins-node
      - keycloak

#Node-Red
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./nodered/data:/data
    networks:
      tooling:
        ipv4_address: 172.16.11.13
    expose:
      - "1880"     

# Nexus
  nexus:
    container_name: nexus
    build: ./nexus
#    image: sonatype/nexus3
    volumes:
      - ./nexus/data:/sonatype-work
    networks:
      tooling:
        ipv4_address: 172.16.11.9
    expose:
      - "8081"     
#    ports:
#      - 922:22/udp
#      - 8082:8081

# FreeIPA
  freeipa:
    container_name: freeipa
    image: freeipa/freeipa-server:centos-8

    restart: always
    hostname: freeipa
    domainname: home.lan
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./freeipa/data:/data:Z 
    expose:
      - "80"
      - "443"
      - "389"
      - "636"
      - "88"
      - "464"
      - "88/udp"
      - "464/udp"
      - "123/udp"
#    ports:
#      - "80:80"       # HTTP
#      - "9444:443"      # HTTPS
#      - "389:389"       # LDAP
#      - "636:636"       # LDAPS
#      - "88:88"         # Kerberos
#      - "464:464"       # Kerberos
#      - "88:88/udp"     # Kerberos
#      - "464:464/udp"   # Kerberos
#      - "123:123/udp"   # ntp

# freeipa.example.com resolves via /etc/hosts

    environment:
      - IPA_SERVER_HOSTNAME=freeipa.home.lan
      - IPA_SERVER_INSTALL_OPTS=-U -r home.lan --no-ntp
      - IPA_SERVER_IP=172.16.11.12
      - PASSWORD=password               # at least 8 characters

      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=freeipa.home.lan
      - VIRTUAL_PORT=80
    dns:
      - 127.0.0.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      tooling:
        ipv4_address: 172.16.11.12
      reverse-proxy: 

# Argos
  argos:
    container_name: argos
    image: argosnotary/argosnotary:1.0.0
    volumes:
      - ./argos/data:/data/db
      - ./argos/config:/data/configdb
    networks:
      tooling:
        ipv4_address: 172.16.11.10    
    ports:
       - 1080:80
       - 8090:8080
       - 8087:8087
    depends_on:
      - keycloak

# AWX

# Keycloak
  keycloak:
    container_name: keycloak
#    image: quay.io/keycloak/keycloak:latest
    build: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: netcicd-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    networks:
      tooling:
        ipv4_address: 172.16.11.11
      keycloak:
    expose:
      - "8080"
#    ports:
#     - 8080:8080
    depends_on:
      - netcicd-db
    
#devmachine
#  vscode:
#    container_name: vscode
#    build: devmachine
#    restart: "no"
#    networks:
#      - jumphosts
#    privileged: false
#    cap_add:
#      - SYS_ADMIN
#    environment:
#      - DISPLAY
#    volumes:
#      - "${HOME}:/home/vscode"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "/tmp/.X11-unix:/tmp/.X11-unix" 