credentials:
  system:
    domainCredentials:
      - credentials:
        - fileSystemServiceAccountCredential:
            id: "1a12dfa4-7fc5-47a7-aa17-cc56572a41c7"
            scope: GLOBAL
        - usernamePassword:
            description: "Credentials to start simulation in VIRL/CML"
            id: "github"
            password: ${GITHUB_PASSWORD}
            scope: GLOBAL
            username: ${GITHUB_USER}
        - usernamePassword:
            description: "Credentials to start simulation in VIRL/CML"
            id: "CML-SIM-CRED"
            password: ${CML_PASSWORD}
            scope: GLOBAL
            username: ${CML_USER}
        - usernamePassword:
            description: "Credentials to be used to log into Jenkins and create agents.\
              \ Username is netcicd, password is ADMIN TOKEN!"
            id: "Jenkins-SIM"
            password: ${JENKINS_AGENT_CREATOR_KEY}
            scope: GLOBAL
            username: ${JENKINS_AGENT_CREATOR}
        - usernamePassword:
            description: "Credentials to be used to log into Gitea from Jenkins to retrieve\
              \ the NetCICD repo."
            id: "git-jenkins"
            password: ${GIT_JENKINS_PASSWORD}
            scope: GLOBAL
            username: "git-jenkins"
        - usernamePassword:
            description: "Credentials to be used to log into Nexus from Jenkins"
            id: "nexus-jenkins"
            password: ${NEXUS_JENKINS_PASSWORD}
            scope: GLOBAL
            username: "nexus-jenkins"
        - usernamePassword:
            description: "Credentials to be used to log into Argos from Jenkins"
            id: "argos-jenkins"
            password: ${ARGOS_JENKINS_PASSWORD}
            scope: GLOBAL
            username: "argos-jenkins"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    roleBased:
      roles:
        agents:
          - name: "jenkins-netcicd-agent"
            pattern: "stage*"
            permissions:
              - "Agent/Provision"
              - "Agent/Configure"
              - "Agent/Build"
              - "Agent/Connect"
              - "Agent/Delete"
              - "Agent/Disconnect"
        global:
          - assignments:
              - "anonymous"
              - "jenkins-readonly"
            name: "jenkins-readonly"
            pattern: ".*"
            permissions:
              - "Overall/Read"
              - "Agent/Connect"
              - "Agent/Disconnect"
          - assignments:
              - "admin"
              - "netcicd"
            name: "jenkins-admin"
            pattern: ".*"
            permissions:
              - "Job/Move"
              - "Job/Build"
              - "Lockable Resources/View"
              - "Credentials/Delete"
              - "Credentials/ManageDomains"
              - "Lockable Resources/Unlock"
              - "View/Create"
              - "Agent/Configure"
              - "Job/Read"
              - "Credentials/Update"
              - "Agent/Create"
              - "Job/Delete"
              - "Agent/Build"
              - "View/Configure"
              - "Lockable Resources/Reserve"
              - "Agent/Provision"
              - "SCM/Tag"
              - "Job/Create"
              - "Job/Discover"
              - "Credentials/View"
              - "Agent/Connect"
              - "Agent/Delete"
              - "Run/Replay"
              - "Agent/Disconnect"
              - "Run/Delete"
              - "Job/Cancel"
              - "Overall/Read"
              - "Run/Update"
              - "Credentials/Create"
              - "Overall/Administer"
              - "View/Delete"
              - "Job/Configure"
              - "Job/Workspace"
              - "View/Read"
              - "Job/ViewStatus"
          - assignments:
            name: "jenkins-user"
            pattern: ".*"
            permissions:
              - "Job/Move"
              - "Job/Build"
              - "Credentials/Delete"
              - "View/Create"
              - "Agent/Configure"
              - "Job/Read"
              - "Credentials/Update"
              - "Agent/Create"
              - "Job/Delete"
              - "Agent/Build"
              - "View/Configure"
              - "Agent/Provision"
              - "SCM/Tag"
              - "Job/Create"
              - "Job/Discover"
              - "Credentials/View"
              - "Agent/Connect"
              - "Agent/Delete"
              - "Run/Replay"
              - "Agent/Disconnect"
              - "Run/Delete"
              - "Job/Cancel"
              - "Overall/Read"
              - "Run/Update"
              - "Credentials/Create"
              - "View/Delete"
              - "Job/Configure"
              - "Job/Workspace"
              - "View/Read"
              - "Job/ViewStatus"
        items:
          - name: "jenkins-netcicd-dev"
            pattern: "^NetCICD$"
            permissions:
              - "Job/Move"
              - "Lockable Resources/View"
              - "Job/Build"
              - "SCM/Tag"
              - "Credentials/Delete"
              - "Job/Create"
              - "Credentials/ManageDomains"
              - "Lockable Resources/Unlock"
              - "Job/Discover"
              - "Job/Read"
              - "Credentials/View"
              - "Credentials/Update"
              - "Run/Replay"
              - "Run/Delete"
              - "Job/Cancel"
              - "Run/Update"
              - "Job/Delete"
              - "Credentials/Create"
              - "Job/Configure"
              - "Job/Workspace"
              - "Lockable Resources/Reserve"
              - "Job/ViewStatus"
          - name: "jenkins-netcicd-toolbox-dev"
            pattern: "^NetCICD-developer-toolbox$"
            permissions:
              - "Job/Move"
              - "Lockable Resources/View"
              - "Job/Build"
              - "SCM/Tag"
              - "Credentials/Delete"
              - "Job/Create"
              - "Credentials/ManageDomains"
              - "Lockable Resources/Unlock"
              - "Job/Discover"
              - "Job/Read"
              - "Credentials/View"
              - "Credentials/Update"
              - "Run/Replay"
              - "Run/Delete"
              - "Job/Cancel"
              - "Run/Update"
              - "Job/Delete"
              - "Credentials/Create"
              - "Job/Configure"
              - "Job/Workspace"
              - "Lockable Resources/Reserve"
              - "Job/ViewStatus"
          - name: "jenkins-netcicd-run"
            pattern: "^NetCICD$"
            permissions:
              - "Lockable Resources/View"
              - "Job/Build"
              - "SCM/Tag"
              - "Lockable Resources/Unlock"
              - "Credentials/View"
              - "Run/Replay"
              - "Job/Cancel"
              - "Run/Delete"
              - "Run/Update"
              - "Job/Workspace"
              - "Lockable Resources/Reserve"
              - "Job/ViewStatus"
          - name: "jenkins-netcicd-toolbox-run"
            pattern: "^NetCICD-developer-toolbox$"
            permissions:
              - "Lockable Resources/View"
              - "Job/Build"
              - "SCM/Tag"
              - "Lockable Resources/Unlock"
              - "Credentials/View"
              - "Run/Replay"
              - "Job/Cancel"
              - "Run/Delete"
              - "Run/Update"
              - "Job/Workspace"
              - "Lockable Resources/Reserve"
              - "Job/ViewStatus"
  clouds:
    - kubernetes:
        addMasterProxyEnvVars: true
        containerCapStr: "100"
        credentialsId: "1a12dfa4-7fc5-47a7-aa17-cc56572a41c7"
        jenkinsTunnel: "172.25.4.115:50000"
        jenkinsUrl: "http://172.25.204.131:8080"
        maxRequestsPerHostStr: "32"
        name: "openshift"
        namespace: "jenkins-operator-system"
        serverCertificate: |-
          -----BEGIN CERTIFICATE-----
          MIIDMjCCAhqgAwIBAgIIC4yFYUPp/78wDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
          CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
          HhcNMjAxMjAzMTIwMDE1WhcNMzAxMjAxMTIwMDE1WjA3MRIwEAYDVQQLEwlvcGVu
          c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
          KoZIhvcNAQEBBQADggEPADCCAQoCggEBAOUWPivRK7aYmUMG94uI35jWPpUeaz9t
          46fxcvUHgduH96bYGBN/oBLQH096nxTfHDnlZtIMhjU/rtcx5bAbLRDI1RP/y5E2
          4i2BYD2dovD7rzL1K5NjNkwHGn51RrNM5sVmCw/Hn+RypKgrMb+7KAveuGxbqfnl
          WRDojm49BcLopZTQHw73rbSQ9wKHodPakcx9hd0+xBXs51lyup/9+MTDfNvlahzl
          ebxVVeDWesm/jcw7ZLl3TLkKwXYhzMOJ7fqiqCUqSAx2B4j0B+HSoHJnMkzimfy2
          HY93Rjp/fl6X27nG/EzonOW3COw1rXl0mZYm6nxpRAAyBDphb0Iu3bMCAwEAAaNC
          MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFNH6
          fDWWrvxXZb/SBnKQCfk0aWvwMA0GCSqGSIb3DQEBCwUAA4IBAQAApZ1RFGxTYnga
          tDO46ThvA6Y5CGEZtIi7KwsGLcnEcdh+iWzSNRbYW00A/H6gXpwbq5D/Mavr5epu
          7Azigbszj6NrdpRP6tSZPmGgtipmZXBlC5eIDL8ulFztr3uC5OHkv6sUecEHmt4V
          F3tdq5IEAQSj5glblLwcqLoB/wSWqqTSwFAYvB99NhDU0piP4mzlTlojU+ej85ag
          MezRB9NDEYUkzxuXHvfYWKaX3zFO3FEQ+5iDcaax4TGxEvxKtz/NcoMIlFT/MffA
          0wmPgmw1i1QVYVJRbFTTTXQxtlPZ8gipORcEwmVAxfJpmJuMplAFezh5fnpdXlt+
          EvW7V8S2
          -----END CERTIFICATE-----
        serverUrl: "https://172.25.0.1:443"
        templates:
          - containers:
              - alwaysPullImage: true
                args: "^${computer.jnlpmac} ^${computer.name}"
                image: "image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven:latest"
                name: "jnlp"
                workingDir: "/tmp"
            label: "maven"
            name: "maven"
            serviceAccount: "jenkins-netcicd"
            slaveConnectTimeoutStr: "0"
            yamlMergeStrategy: "override"
          - containers:
              - alwaysPullImage: true
                args: "^${computer.jnlpmac} ^${computer.name}"
                image: "image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-nodejs:latest"
                name: "jnlp"
                workingDir: "/tmp"
            label: "nodejs"
            name: "nodejs"
            serviceAccount: "jenkins-netcicd"
            slaveConnectTimeoutStr: "0"
            yamlMergeStrategy: "override"
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: "CML_URL"
            value: "http://192.168.0.57"
  labelAtoms:
    - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodes:
    - permanent:
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
        name: "jenkins_node"
        nodeDescription: "Jenkins Worker node"
        remoteFS: "/root/jenkins_slave"
        retentionStrategy: "always"
  noUsageStatistics: true
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 1
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm: "openShiftOAuth2"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
    - list:
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastSuccess"
          - "lastFailure"
          - "lastDuration"
          - "buildButton"
          - "favoriteColumn"
        includeRegex: "((?!seed)(?!jenkins).)*"
        name: "non-seed-jobs"
    - list:
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastSuccess"
          - "lastFailure"
          - "lastDuration"
          - "buildButton"
          - "favoriteColumn"
        includeRegex: ".*job-dsl-seed.*"
        name: "seed-jobs"
  viewsTabBar: "standard"
jobs:
  - script: >
      multibranchPipelineJob('image-jenkins') {
        branchSources {
          github {
            // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
            id('12312313') // IMPORTANT: use a constant and unique identifier
            scanCredentialsId('github')
            repoOwner('85matthew')
            repository('NetCICD')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(1)
          }
        }
        triggers {
          periodic(5)
        }
      }

security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  scriptApproval:
    approvedSignatures:
      - "method hudson.slaves.SlaveComputer getJnlpMac"
      - "method jenkins.model.Jenkins getComputer java.lang.String"
      - "staticMethod jenkins.model.Jenkins getInstance"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketCloudEndpoint:
          enableCache: false
          manageHooks: false
          repositoriesCacheDuration: 0
          teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  defaultFolderConfiguration:
    healthMetrics:
      - worstChildHealthMetric:
          recursive: true
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "https://jenkins-netcicd-jenkins-operator-system.apps-crc.testing/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalPluginConfiguration:
    buildConfigListInterval: 300
    buildListInterval: 300
    configMapListInterval: 300
    enabled: true
    foldersEnabled: true
    imageStreamListInterval: 300
    namespace: "jenkins-operator-system"
    secretListInterval: 300
  location:
    adminAddress: "nobody@nowhere"
    url: "https://jenkins-netcicd-jenkins-operator-system.apps-crc.testing"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  prometheusConfiguration:
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
